name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gha-oidc-tests:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dump env
      run: env
    - name: Post the token
      run: |
        echo "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s"
        X=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
        Y=$(base64 <<< $X)
        echo $Y
